name: CD 2 - deployreport on staging from main

on:
  push:
    branches:
      - main
    paths:
      - 'ContosoOutdoors/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 'checkout code'
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0

      # build the project into a dacpac file
      - name: Setup .NET
        uses: actions/setup-dotnet@67a3573c9a986a3f9c594539f4ab511d57bb3ce9 # v4.3.1
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore

      # generate a deployment report
      - name: 'Deploy dacpac'
        run: sqlpackage /a:deployreport /sf:'bin/Debug/ContosoOutdoors.dacpac' /tcs:"${{ secrets.STAGING_CONNECTION_STRING }};" /OutputPath:DeployReport.xml
        working-directory: ContosoOutdoors
      

      # save the deployment script as an artifact
      - name: 'Save deployment script'
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: deployment-report
          path: ContosoOutdoors/DeployReport.xml

      - name: Check for alerts
        run: ./check-for-alerts.sh
