name: CD 4 - Build and generate deployment script from main for prod environment

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 'checkout code'
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      # build the project into a dacpac file
      - name: Setup .NET
        uses: actions/setup-dotnet@a98b56852c35b8e3190ac28c8c2271da59106c68 # v6.0.0
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore

      # generate a deployment script
      - name: 'Deploy dacpac'
        run: sqlpackage /a:Script /sf:'bin/Debug/ContosoOutdoors.dacpac' /tcs:"${{ secrets.PROD_CONNECTION_STRING }};" /dsp:'deployment-script.sql'
        working-directory: ContosoOutdoors
    
      # save the deployment script as an artifact
      - name: 'Save deployment script'
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: deployment-script
          path: ContosoOutdoors/deployment-script.sql

